# Generated by Django 6.0.6 on 2026-06-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='contraseña', max_length=255),
        ),
    ]
