# Generated by Django 6.0.2 on 2026-04-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_calificacion_fecha_alter_calificacion_puntuacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordencompra',
        ),
    ]
