# Generated by Django 6.0.6 on 2026-06-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_delete_ordencompra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='password', max_length=255),
        ),
    ]
