# Generated by Django 6.0.6 on 2026-06-16 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        ('pqrs', '0003_create_pqrsf_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fechaenvio', models.DateTimeField(auto_now_add=True, db_column='fechaEnvio')),
                ('leida', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('pqrsf', 'PQRSF'), ('carrito', 'Carrito / Pedido'), ('sistema', 'Sistema'), ('stock', 'Stock bajo')], default='sistema', max_length=20)),
                ('carrito', models.ForeignKey(blank=True, db_column='id_carrito', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.carrito')),
                ('pqrsf', models.ForeignKey(blank=True, db_column='pqrsf_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pqrs.pqrsf')),
                ('usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fechaenvio'],
                'managed': True,
            },
        ),
    ]
