# Generated by Django 6.0.2 on 2026-04-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_proveedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor-Producto',
                'db_table': 'proveedor_producto',
                'managed': False,
            },
        ),
    ]
