# Generated by Django 6.0.6 on 2026-06-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedorproducto',
            options={'managed': True, 'verbose_name': 'Proveedor-Producto'},
        ),
    ]
