# Generated by Django 6.0.6 on 2026-06-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrsf',
            options={'managed': True, 'verbose_name': 'PQRSF', 'verbose_name_plural': 'PQRSFs'},
        ),
    ]
