# Generated by Django 6.0.2 on 2026-04-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='orden',
            field=models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordencompra.ordencompra'),
        ),
    ]
